version: '1'
services:
    backend:
        build: 
          context: backend
        stop_signal: SIGINT
        ports:
          - 8000:8000
        environment:
          FLASK_APP: backend.py
        restart: always
        networks:
          - db_net
        volumes:
          - ~/.aws/:/root/.aws/:ro
    db:
        build: 
          context: db
        stop_signal: SIGINT
        ports:
          - 3306:3306
        restart: always
        networks:
          - db_net
        volumes:
          - db_vol:/var/lib/mysql
    
#    gpt:
#        build: 
#          context: chat_gpt
#        stop_signal: SIGINT
#        ports:
#          - 5000:5000
#        environment:
#          FLASK_APP: gpt_plugin.py
#        restart: always
#        networks:
#          - db_net
#        volumes:
#          - ~/.aws/:/root/.aws/:ro
#        

networks:
    db_net:
volumes:
    db_vol:


